### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by DioguitoM11** [zencq/NomNom#162] opened 2024-03-05 23:26 UTC
The new pre realeases have a bug where if you click the no mans sky assistant button it would crash

**Comment by DioguitoM11** [comment] 2024-03-05 23:30
Its on beta.6

**Comment by cengelha** [comment] 2024-03-07 21:25
Did you click the button while a pre-Omega save was selected? They are currently not supported by beta.5 and up

**Comment by cengelha** [comment] 2024-03-07 21:27
Also, probably a duplicate of #159

**Closed by cengelha** 2024-03-07 21:27 UTC
Labels: bug
