### ISSUE TITLE
[Bug] Editor does not function on clean install

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [zencq/NomNom#220] opened 2024-11-01 23:56 UTC
### Description
The editor opens a super-tall welcome window with no text on first run and then nothing in the editor itself works. It is all grayed out. Setting paths does not seem to fix anything. Every file is dated 12/31/1979 for some reason, making them older than I am by about six months. In the zip file they're dating 12/31/1899. Did Arthur Morgan and John Marston use this during their down time?

### Reproduce
1. Download portable version
2. Extract it somewhere, like a folder on your desktop
3. Run the editor

### Expected Behavior
I expected the editor to start, detect my saves, and allow me to view and/or edit them

### Files
It doesn't crash so I have no crash dump or anything

### Additional Context
Add any other context about the problem here or at least complete the following information.
 - Version: 5.20.0
 - Platform: Steam

**Comment by Troll00Dragon** [comment] 2024-11-02 19:18
Exactly the same here with the windows installer version, tall empty welcome window and nothing works.

**Comment by cengelha** [comment] 2024-11-08 08:04
I don't how people conclude that this project isn't active or there is no movement when is says maintained=yes on the main page, there was a release 2 weeks ago, and this issue for example is just a week old (no offense). The problem/behavior of the app this there much longer than this issue, true, but just because one bug isn't resolve immediately it doesn't mean the project is abandoned.

I can't really tell you why the welcome window opens empty/no platforms are auto-detected for some but usually it should work when you just close it and then manually set a path via menu _File -> Open_. As that workaround worked in the past, I didn't work on this one yet.

If it doesn't work, let me know and may attach the log if there is no crash report.

**Comment by The-Great-Sephiroth** [comment] 2024-11-08 20:04
I am looking at the main page and most components are many months old. When I open the page I see 9 months, 4 years, 3 months, 2 weeks (this appears to be only the changelog), and four more that are months or years old. This is why I asked.

[Velopack.log](https://github.com/user-attachments/files/17683537/Velopack.log)

There's the log. I should note that I tried with both the 32bit .NET6 and 64bit .NET6 separately and with both installed.

**Comment by Troll00Dragon** [comment] 2024-11-09 16:27
I managed to get it working by manually opening a save file.  I also found NMSSaveEditor by goatfungus and it seems to work much better.  I might try NomNom again if it gets updated.

**Comment by The-Great-Sephiroth** [comment] 2024-11-09 22:49
NMSSaveEditor is one I have used many times and I like it, but it's down right now. Since the save format changed something happened and his repo appears to be offline, showing no releases at all. I would not advise using the old one.

**Comment by Troll00Dragon** [comment] 2024-11-09 22:57
Thanks for the info. I have not used it to change a save, just to look around.  I'll not use it with an active save until it's back online again.

**Comment by wkitty42** [comment] 2024-11-10 01:52
> NMSSaveEditor is one I have used many times and I like it, but it's down right now. Since the save format changed something happened and his repo appears to be offline, showing no releases at all. I would not advise using the old one.

it is working fine for me and his github repo still seems to be alive... i'm not sure what you are looking at... the last update was two weeks ago for Expedition 16: The Cursed...

**Comment by The-Great-Sephiroth** [comment] 2024-11-10 16:05
It does appear to work, but two things changed two weeks ago. One is that save names on the save selection drop-down are now blank, and some of mine say "EMPTY" instead of survival/expedition/whatever. The other is that if you edit a save with NMSSE, when you go into the game to load your save, the time played, date, where you're at, etc is all gone. It's just missing.

**Comment by cengelha** [comment] 2024-11-10 22:16
@The-Great-Sephiroth I see, thanks for clarification! As there is not source code (yet), the CHANGELOG file is the only file that gets updated at the moment. But the maintained=yes is there for a reason and the [releases](https://github.com/zencq/NomNom/releases) are what you should look at if you want to know if there are any recent updates.

GF has no source code up either but puts his binaries in the repo itself, so they change/have a recent timestamp. But in my option, it's the wrong place to place them (with or without source code) so I'm not doing it but the actual GitHub releases.

Back to topic: I don't know whether there is a quick fix, but as mentioned the workaround usually works, but I'm working on something that should also fix this (but still takes a while).

**Comment by cengelha** [comment] 2024-11-10 22:19
This https://github.com/zencq/NomNom/issues/155 and this https://github.com/zencq/NomNom/issues/163 may also be relevant /related.

**Comment by cengelha** [comment] 2024-12-01 16:05
The cause of not detecing the platforms in the first place is prolly not resolved but I changed it in a way that the super-tall welcome window isn't super-tall in any case and added some button to directly add the PC default paths manually.

**Closed by cengelha** 2024-12-01 16:05 UTC
Labels: bug
