### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by vrcxx** [zencq/NomNom#157] opened 2024-02-25 23:22 UTC
### Description
I cannot edit the freighter, frigate list, base building or planetary settlement, the tab remains light grey and i cannot even click on it

### Reproduce
1) open nomnom
2) load saves
3) can edit most of the things but not the freighter

**Comment by cengelha** [comment] 2024-03-07 21:29
Duplicate of #160

**Closed by cengelha** 2024-03-07 21:29 UTC
Labels: bug
